config/routes.rb
Rails.application.routes.draw do

  get 'users/new'

  root 'houses#map'
  get 'visualisation/scatter'
  # get 'visualisation/bar'
  get 'visualisation/heatmap'
  get 'visualisation/tableau'

  post 'sessions/login' => 'sessions#create'
  delete 'sessions/logout' => 'sessions#destroy'

  resources :houses, only: [:create, :index, :show] do
    collection do
      get 'export'
      get 'filter'
      get 'return_houses'
      get 'return_nums_prices'
    end
    member do
      get 'nearby'
    end
  end

  resources :spiders, only: [:create, :index] do
    collection do
      get 'do_background'
      get 'pause_background'
      get 'return_next'
      get 'export_bus'
      get 'export_bus_house'
    end
  end

  resources :hospitals, only: [:create, :index] do
    collection do
      get 'ajax'
    end
  end

  get '/signup', to: 'users#new'
  resources :users
  resources :account_activations, only: [:edit]


  

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController

  def index
    @houses=House.search(search_params).order('id').paginate(:page => params[:page], :per_page => 20)
    
  end

  def map
  end

  def filter_null
    @houses=House.where('houses.latitude' => nil, 'houses.longitude' => nil)
    @houses.each do |house|
      house.destroy
    end
    redirect_to houses_path, flash: {:success => '成功删除'}
  end

  def return_houses
    houses=House.filter(params)
    respond_to do |format|
      format.json { render :json => houses }
    end
  end

  # for scatter plot
  def return_nums_prices
    houses=House.limit(10)
    nums_prices=houses.map { |house| [house.buses.length,house.hospitals.length, house.shops.length,
                                      house.works.length, house.schools.length, house.subways.length,
                                      house.average_price] }
    respond_to do |format|
      format.json { render :json => nums_prices }
    end

  end

  def nearby
    house=House.find_by_id(params[:id])

    data=house.buses if params[:type]=='bus'
    data=house.works if params[:type]=='work'
    data=house.hospitals if params[:type]=='hospital'
    data=house.subways if params[:type]=='subway'
    data=house.shops if params[:type]=='shop'
    data=house.schools if params[:type]=='school'

    respond_to do |format|
      format.json { render :json => data }
    end
  end

  def show
    @house=House.find_by_id(params[:id])
  end

  def export
    @house=House.all
    respond_to do |format|
      format.xlsx { render "二手房数据_#{DateTime.now}", template: "houses/export.xlsx.axlsx" }
      format.csv { send_data @houses.to_csv, filename: "houses-#{Date.today}.csv" }
    end
  end

  private
  def search_params
    params[:query]
  end

end

app/helpers/houses_helper.rb
module HousesHelper

  def average_distance(items)
    return 0 if items.length == 0
    items.map(&:distance).sum/items.length
  end

  def insert(house, params, obj, asso_obj, asso_type)
    params[:nearby_info].split(',').each do |row|
      attr=row.split('/')
      bus=obj.find_by(longitude: attr[1], latitude: attr[2])
      if bus.nil?
        bus=obj.new(name: attr[0], longitude: attr[1], latitude: attr[2])
        bus.save
      end
      asso_obj.create("#{asso_type}_id": bus.id, house_id: house.id, distance: attr[3])
    end
  end

  def date_and_price(prices)
    a=[]
    for p in prices
      a.append({'date'=>p['date'].strftime('%Y-%m-%d'),'price'=>p['price'].to_s})
    end
    a
    
  end

end

app/views/houses/_item.html.erb
<div class="col-lg-2 col-md-6">
  <div id="map-detail" class="panel panel-<%= color %>">
    <div class="panel-heading">
      <div class="row">
        <div class="col-xs-3">
          <i class="<%= icon %>"></i>
        </div>
        <div class="col-xs-9 text-right">
          <div class="huge"><%= num %></div>
          <div><%= type %></div>
        </div>
      </div>
    </div>
    <a path="<%= link %>" href="#">
      <div class="panel-footer">
        <span class="pull-left">View Details</span>
        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
        <div class="clearfix"></div>
      </div>
    </a>
  </div>
</div>

app/views/houses/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">数据列表</h1>
  </div>
</div>
<div class="row">
<div class="col-lg-12">
<div class="panel panel-default">
  <div class="panel-heading">
    <text class="panel-title">汇总数据</text>
    <div class="pull-right">
      <%= link_to "删除无坐标数据", filter_houses_path, class: "btn btn-danger btn-xs", style: "margin-right:5px;" %>
      <%= form_tag export_houses_path(:format => :csv), :method => :get, class: "pull-right", style: "margin-right:5px;" do %>
          <%= hidden_field_tag :query, params[:query] %>
          <%= button_tag(type: "submit", class: "btn btn-success btn-xs") do %>
              <span class="glyphicon glyphicon-floppy-save"></span> 导出
          <% end %>
      <% end %>

      <%#= form_tag export_buses_path(:format => :csv), :method => :get, class: "pull-right", style: "margin-right:5px;" do %>
      <%#= button_tag(type: "submit", class: "btn btn-success btn-xs") do %>
      <!--<span class="glyphicon glyphicon-floppy-save"></span> 导出公交数据-->
      <%# end %>
      <%# end %>


    </div>
  </div>
  <div class="panel-body" style="min-height:750px">

    <% unless params[:query].blank? %>
        <div class="row">
          <div class="col-sm-12">
            <text class="text-danger">搜索结果显示:
              <mark><%= params[:query] %></mark>
            </text>
          </div>
        </div>
        <hr>
    <% end %>

    <table class="table table-responsive table-condensed table-hover">
      <thead>
      <tr>
        <th>ID</th>
        <th>小区名</th>
        <!--<th>街道</th>-->
        <th>建造时间</th>
        <th>楼层</th>
        <th>面积</th>
        <th>房型</th>
        <!--<th>经度</th>-->
        <!--<th>纬度</th>-->
        <th>医院</th>
        <th>公交</th>
        <th>商场</th>
        <th>地铁</th>
        <th>学校</th>
        <th>写字楼</th>
        <th>每平米价格</th>

      </tr>
      </thead>
      <tbody>
      <% @houses.each do |house| %>
          <tr>
            <td>
              <text style="font-size: small"><%= house.id %></text>
            </td>
            <td>
              <text style="font-size: small"><%= link_to "#{house.community}", house_path(house), method: :get %></text>
            </td>
            <td>
              <text style="font-size: small"><%= house.build_time %></text>
            </td>
            <td>
              <text style="font-size: small"><%= house.floor %></text>
            </td>
            <td>
              <text style="font-size: small"><%= house.area %></text>
            </td>
            <td>
              <text style="font-size: small"><%= house.room_shape %></text>
            </td>
            <!--<td>-->
            <!--<text style="font-size: small"><%#= house.latitude %></text>-->
            <!--</td>-->
            <!--<td>-->
            <!--<text style="font-size: small"><%#= house.longitude %></text>-->
            <!--</td>-->
            <td>
              <text style="font-size: small"><%= house.hospitals.length %></text>
            </td>
            <td>
              <text style="font-size: small"><%= house.buses.length %></text>
            </td>
            <td>
              <text style="font-size: small"><%= house.shops.length %></text>
            </td>
            <td>
              <text style="font-size: small"><%= house.subways.length %></text>
            </td>
            <td>
              <text style="font-size: small"><%= house.schools.length %></text>
            </td>
            <td>
              <text style="font-size: small"><%= house.works.length %></text>
            </td>
            <td>
              <text style="font-size: small"><%= house.average_price %></text>
            </td>

          </tr>
      <% end %>


      </tbody>
    </table>

    <%= will_paginate @houses, :param_name => 'page',
                      :previous_label => t("前一页"), :next_label => t("后一页"), :inner_window => 1 %>

  </div>
</div>
</div> 
</div>

app/views/houses/map.html.erb
</br>
<div class="row">

  <div class="col-sm-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <i class="fa fa-bar-chart-o fa-fw"></i> 北京房价总体分布图
      </div>
      <div class="panel panel-body">
        <div id="main" style="width: 100%;height:500px;"></div>
      </div>
    </div>
  </div>

  <div class="col-sm-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <i class="fa fa-search fa-fw"></i> 基本筛选
      </div>
      <div class="panel panel-body">

        <form class="form">
          <div class="form-group">
            <label>每平米价格(±1.5万):</label>
            <%= text_field_tag 'average_price', params[:price], class: "form-control input-sm" %>
          </div>

          <div class="form-group">
            <label>面积大小(±20):</label>
            <%= text_field_tag 'area', params[:area], class: "form-control input-sm" %>
          </div>

          <div class="form-group">
            <label>房型:</label>
            <%#= select_tag 'room_shape', options_for_select(House.select(:room_shape).map(&:room_shape).uniq, ""), class: "form-control input-sm" %>
            <%= text_field_tag 'room_shape', params[:room_shape], class: "form-control input-sm" %>
          </div>

          <div class="form-group">
            <label>建造时间(年):</label>
            <%= text_field_tag 'build_time', params[:build_time], class: "form-control input-sm" %>
          </div>

          <div class="form-group">
            <label>地址:</label>
            <%= text_field_tag 'street', params[:street], class: "form-control input-sm" %>
          </div>

          <button class="btn btn-success btn-block">查询</button>

        </form>

        <button onclick="reset();" type="button" class="btn btn-primary btn-block" style="margin-top: 10px;">重置</button>

      </div>
    </div>
  </div>

</div>

<script>
    var myChart = echarts.init(document.getElementById('main'));

    // 默认筛选空
    draw('', '', '', '', '');

    // 点击提交表单后，由ajax的draw负责
    $('form').submit(function () {
        var params = $(this).serializeArray();
        var price = params[0].value;
        var area = params[1].value;
        var room_shape = params[2].value;
        var build_time = params[3].value;
        var street = params[4].value;
        draw(price, area, room_shape, build_time, street, distance);
        return false; // prevents normal behaviour
    });


    function reset() {
        draw('', '', '', '', '');
    }

    // 查询符合条件的房屋并画出
    function draw(price, area, room_shape, build_time, street) {
        $.ajax({
            type: "GET",
            url: "/houses/return_houses",
            data: "price=" + price + "&area=" + area + "&room_shape=" + room_shape + "&build_time=" + build_time + "&street=" + street,
            dataType: 'json',
            success: function (data) {
                myChart.hideLoading();
                var house_data = [];

                // 对所有的house进行遍历，按照一定的格式构造每个house的信息
                $.each(data, function (index, house) {
                    var each_house = [];
                    each_house.push(house.longitude, house.latitude, house.id, house.average_price / 10000, house.community, house.area, house.room_shape, house.floor, house.build_time, house.street);
                    house_data.push(each_house);
                });

                // 点击后到跳到具体的房屋信息里
                myChart.on('click', function (params) {
                    window.open("/houses/" + encodeURIComponent(params.value[2]));
                });

                // 在百度地图中画出来
                myChart.setOption({
                    backgroundColor: '#404a59',
                    tooltip: {
                        padding: 10,
                        backgroundColor: '#222',
                        borderColor: '#777',
                        borderWidth: 1,
                        trigger: 'item',
                        formatter: function (obj) {
                            var value = obj.value;
                            return '<div style="border-bottom: 1px solid rgba(255,255,255,.3); font-size: 18px;padding-bottom: 7px;margin-bottom: 7px">'
                                + value[4] + ': ' + value[3] + "万"
                                + '</div>'
                                + '面积: ' + value[5] + '<br>'
                                + '房型：' + value[6] + '<br>'
                                + '楼层：' + value[7] + '<br>'
                                + '建造时间：' + value[8] + '<br>'
                                + '地址：' + value[9] + '<br>'
                                + '距离天安门：' + value[10] + '<br>';

                        }
                    },
                    legend: {
                        orient: 'vertical',
                        y: 'bottom',
                        x: 'right',
                        data: ['价格'],
                        textStyle: {
                            color: '#fff'
                        }
                    },
                    visualMap: {
                        left: 'right',
                        bottom: '0%',
                        min: 0,
                        max: 13,
                        dimension: 3,
                        precision: 0.1,
                        text: ['每平方米/万'],
                        textGap: 20,
                        calculable: true,
                        inRange: {
                            color: ['#50a3ba', '#eac736', 'red']
                        },
                        textStyle: {
                            color: '#fff'
                        }
                    },

                    bmap: {
                        center: [116.404, 39.915],
                        zoom: 11,
                        roam: true,
                        mapStyle: {
                            'styleJson': [
                                {
                                    'featureType': 'water',
                                    'elementType': 'all',
                                    'stylers': {
                                        'color': '#031628'
                                    }
                                },
                                {
                                    'featureType': 'land',
                                    'elementType': 'geometry',
                                    'stylers': {
                                        'color': '#000102'
                                    }
                                },
                                {
                                    'featureType': 'highway',
                                    'elementType': 'all',
                                    'stylers': {
                                        'visibility': 'off'
                                    }
                                },
                                {
                                    'featureType': 'arterial',
                                    'elementType': 'geometry.fill',
                                    'stylers': {
                                        'color': '#000000'
                                    }
                                },
                                {
                                    'featureType': 'arterial',
                                    'elementType': 'geometry.stroke',
                                    'stylers': {
                                        'color': '#0b3d51'
                                    }
                                },
                                {
                                    'featureType': 'local',
                                    'elementType': 'geometry',
                                    'stylers': {
                                        'color': '#000000'
                                    }
                                },
                                {
                                    'featureType': 'railway',
                                    'elementType': 'geometry.fill',
                                    'stylers': {
                                        'color': '#000000'
                                    }
                                },
                                {
                                    'featureType': 'railway',
                                    'elementType': 'geometry.stroke',
                                    'stylers': {
                                        'color': '#08304b'
                                    }
                                },
                                {
                                    'featureType': 'subway',
                                    'elementType': 'geometry',
                                    'stylers': {
                                        'lightness': -70
                                    }
                                },
                                {
                                    'featureType': 'building',
                                    'elementType': 'geometry.fill',
                                    'stylers': {
                                        'color': '#000000'
                                    }
                                },
                                {
                                    'featureType': 'all',
                                    'elementType': 'labels.text.fill',
                                    'stylers': {
                                        'color': '#857f7f'
                                    }
                                },
                                {
                                    'featureType': 'all',
                                    'elementType': 'labels.text.stroke',
                                    'stylers': {
                                        'color': '#000000'
                                    }
                                },
                                {
                                    'featureType': 'building',
                                    'elementType': 'geometry',
                                    'stylers': {
                                        'color': '#022338'
                                    }
                                },
                                {
                                    'featureType': 'green',
                                    'elementType': 'geometry',
                                    'stylers': {
                                        'color': '#062032'
                                    }
                                },
                                {
                                    'featureType': 'boundary',
                                    'elementType': 'all',
                                    'stylers': {
                                        'color': '#465b6c'
                                    }
                                },
                                {
                                    'featureType': 'manmade',
                                    'elementType': 'all',
                                    'stylers': {
                                        'color': '#022338'
                                    }
                                },
                                {
                                    'featureType': 'label',
                                    'elementType': 'all',
                                    'stylers': {
                                        'visibility': 'off'
                                    }
                                }
                            ]
                        }
                    },
                    series: [{
                        name: 'house',
                        type: 'scatter',
                        coordinateSystem: 'bmap',
                        data: house_data,
                        symbolSize: 12,
                        pointSize: 5,
                        blurSize: 6,
                        label: {
                            normal: {
                                show: false
                            },
                            emphasis: {
                                show: false
                            }
                        },
                        itemStyle: {
                            emphasis: {
                                borderColor: '#fff',
                                borderWidth: 1
                            },
                            normal: {
                                opacity: 0.8
                            }
                        }
                    }]
                });
            },
            error: function () {
                alert('error')
            },
            timeout: function () {
                alert('time out')
            }
        });
    }


</script>